# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 686)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("photo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 291, 641))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(291, 641))
        self.treeWidget.setMaximumSize(QtCore.QSize(291, 641))
        self.treeWidget.setAcceptDrops(False)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "Manu")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 610, 51, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRemote = QtWidgets.QMenu(self.menuFile)
        self.menuRemote.setObjectName("menuRemote")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_Recent = QtWidgets.QAction(MainWindow)
        self.actionOpen_Recent.setObjectName("actionOpen_Recent")
        self.actionMerge = QtWidgets.QAction(MainWindow)
        self.actionMerge.setObjectName("actionMerge")
        self.actionWatch_Pattern = QtWidgets.QAction(MainWindow)
        self.actionWatch_Pattern.setObjectName("actionWatch_Pattern")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave_Meth = QtWidgets.QAction(MainWindow)
        self.actionSave_Meth.setObjectName("actionSave_Meth")
        self.actionSave_Mesh = QtWidgets.QAction(MainWindow)
        self.actionSave_Mesh.setObjectName("actionSave_Mesh")
        self.actionSave_Module = QtWidgets.QAction(MainWindow)
        self.actionSave_Module.setObjectName("actionSave_Module")
        self.actionSave_Options_As_Default = QtWidgets.QAction(MainWindow)
        self.actionSave_Options_As_Default.setObjectName("actionSave_Options_As_Default")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionPlugins = QtWidgets.QAction(MainWindow)
        self.actionPlugins.setObjectName("actionPlugins")
        self.actionVisibility = QtWidgets.QAction(MainWindow)
        self.actionVisibility.setObjectName("actionVisibility")
        self.actionClipping = QtWidgets.QAction(MainWindow)
        self.actionClipping.setObjectName("actionClipping")
        self.actionManipulator = QtWidgets.QAction(MainWindow)
        self.actionManipulator.setObjectName("actionManipulator")
        self.actionStatitics = QtWidgets.QAction(MainWindow)
        self.actionStatitics.setObjectName("actionStatitics")
        self.actionMessage_Consol = QtWidgets.QAction(MainWindow)
        self.actionMessage_Consol.setObjectName("actionMessage_Consol")
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionMerge_2 = QtWidgets.QAction(MainWindow)
        self.actionMerge_2.setObjectName("actionMerge_2")
        self.actionClear_2 = QtWidgets.QAction(MainWindow)
        self.actionClear_2.setObjectName("actionClear_2")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionNew_Window = QtWidgets.QAction(MainWindow)
        self.actionNew_Window.setObjectName("actionNew_Window")
        self.actionCopy_To_Clip_Board = QtWidgets.QAction(MainWindow)
        self.actionCopy_To_Clip_Board.setObjectName("actionCopy_To_Clip_Board")
        self.actionHorizontally = QtWidgets.QAction(MainWindow)
        self.actionHorizontally.setObjectName("actionHorizontally")
        self.actionSplit_Vertically = QtWidgets.QAction(MainWindow)
        self.actionSplit_Vertically.setObjectName("actionSplit_Vertically")
        self.actionUnsplit = QtWidgets.QAction(MainWindow)
        self.actionUnsplit.setObjectName("actionUnsplit")
        self.actionMinimize = QtWidgets.QAction(MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionZoom = QtWidgets.QAction(MainWindow)
        self.actionZoom.setObjectName("actionZoom")
        self.actionEnter_Full_Screen = QtWidgets.QAction(MainWindow)
        self.actionEnter_Full_Screen.setObjectName("actionEnter_Full_Screen")
        self.actionAttach_Detach_Manu = QtWidgets.QAction(MainWindow)
        self.actionAttach_Detach_Manu.setObjectName("actionAttach_Detach_Manu")
        self.actionBring_All_To_Front = QtWidgets.QAction(MainWindow)
        self.actionBring_All_To_Front.setObjectName("actionBring_All_To_Front")
        self.actionOnline_Document = QtWidgets.QAction(MainWindow)
        self.actionOnline_Document.setObjectName("actionOnline_Document")
        self.actionKeyboard_And_Mouse_Usage = QtWidgets.QAction(MainWindow)
        self.actionKeyboard_And_Mouse_Usage.setObjectName("actionKeyboard_And_Mouse_Usage")
        self.actionCurrent_Option_And_Space = QtWidgets.QAction(MainWindow)
        self.actionCurrent_Option_And_Space.setObjectName("actionCurrent_Option_And_Space")
        self.actionRestore_all_Options_to_Default_Setting = QtWidgets.QAction(MainWindow)
        self.actionRestore_all_Options_to_Default_Setting.setObjectName("actionRestore_all_Options_to_Default_Setting")
        self.actionAbout_OnelabClient = QtWidgets.QAction(MainWindow)
        self.actionAbout_OnelabClient.setObjectName("actionAbout_OnelabClient")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.menuRemote.addAction(self.actionStart)
        self.menuRemote.addAction(self.actionMerge_2)
        self.menuRemote.addAction(self.actionClear_2)
        self.menuRemote.addAction(self.actionStop)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_Recent)
        self.menuFile.addAction(self.actionMerge)
        self.menuFile.addAction(self.actionWatch_Pattern)
        self.menuFile.addAction(self.actionClear)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuRemote.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionSave_Meth)
        self.menuFile.addAction(self.actionSave_Mesh)
        self.menuFile.addAction(self.actionSave_Module)
        self.menuFile.addAction(self.actionSave_Options_As_Default)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionDelete)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionOptions)
        self.menuEdit.addAction(self.actionPlugins)
        self.menuEdit.addAction(self.actionVisibility)
        self.menuEdit.addAction(self.actionClipping)
        self.menuEdit.addAction(self.actionManipulator)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionStatitics)
        self.menuEdit.addAction(self.actionMessage_Consol)
        self.menuWindow.addAction(self.actionNew_Window)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionCopy_To_Clip_Board)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionHorizontally)
        self.menuWindow.addAction(self.actionSplit_Vertically)
        self.menuWindow.addAction(self.actionUnsplit)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionMinimize)
        self.menuWindow.addAction(self.actionZoom)
        self.menuWindow.addAction(self.actionEnter_Full_Screen)
        self.menuWindow.addAction(self.actionAttach_Detach_Manu)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionBring_All_To_Front)
        self.menuHelp.addAction(self.actionOnline_Document)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionKeyboard_And_Mouse_Usage)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionCurrent_Option_And_Space)
        self.menuHelp.addAction(self.actionRestore_all_Options_to_Default_Setting)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_OnelabClient)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Onelab Client"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Module"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Geometry"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "Elementary entities"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).setText(0, _translate("MainWindow", "Add"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).child(0).setText(0, _translate("MainWindow", "Parameter"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).child(1).setText(0, _translate("MainWindow", "Point"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).child(2).setText(0, _translate("MainWindow", "Straight line"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).child(3).setText(0, _translate("MainWindow", "Spline"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).child(4).setText(0, _translate("MainWindow", "B-Spline"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).child(5).setText(0, _translate("MainWindow", "Circle arc"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).child(6).setText(0, _translate("MainWindow", "Ellipse arc"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).child(7).setText(0, _translate("MainWindow", "Plane surface"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).child(8).setText(0, _translate("MainWindow", "Ruled surface"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).child(9).setText(0, _translate("MainWindow", "Volume"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).setText(0, _translate("MainWindow", "Translate"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).child(0).setText(0, _translate("MainWindow", "Point"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).child(1).setText(0, _translate("MainWindow", "Line"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).child(2).setText(0, _translate("MainWindow", "Surface"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).child(3).setText(0, _translate("MainWindow", "Volume"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).child(4).setText(0, _translate("MainWindow", "Duplicate point"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).child(5).setText(0, _translate("MainWindow", "Duplicate line"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).child(6).setText(0, _translate("MainWindow", "Duplicate surface"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).child(7).setText(0, _translate("MainWindow", "Duplicate volume"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).child(8).setText(0, _translate("MainWindow", "Extrude point"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).child(9).setText(0, _translate("MainWindow", "Extrude line"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).child(10).setText(0, _translate("MainWindow", "Extrude surface"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(2).setText(0, _translate("MainWindow", "Rotate"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(2).child(0).setText(0, _translate("MainWindow", "Point"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(2).child(1).setText(0, _translate("MainWindow", "Line"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(2).child(2).setText(0, _translate("MainWindow", "Surface"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(2).child(3).setText(0, _translate("MainWindow", "Duplicate point"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(2).child(4).setText(0, _translate("MainWindow", "Duplicate line"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(2).child(5).setText(0, _translate("MainWindow", "Duplicate surface"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(2).child(6).setText(0, _translate("MainWindow", "Duplicate volume"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(2).child(7).setText(0, _translate("MainWindow", "Extrude point"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(2).child(8).setText(0, _translate("MainWindow", "Extrude line"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(2).child(9).setText(0, _translate("MainWindow", "Extrude surface"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(3).setText(0, _translate("MainWindow", "Scale"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(3).child(0).setText(0, _translate("MainWindow", "Point"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(3).child(1).setText(0, _translate("MainWindow", "line"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(3).child(2).setText(0, _translate("MainWindow", "Surface"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(3).child(3).setText(0, _translate("MainWindow", "Volume"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(3).child(4).setText(0, _translate("MainWindow", "Duplicate point"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(3).child(5).setText(0, _translate("MainWindow", "Duplicate line"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(3).child(6).setText(0, _translate("MainWindow", "Duplicate surface"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(3).child(7).setText(0, _translate("MainWindow", "Duplicate volume"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(4).setText(0, _translate("MainWindow", "Symmetry"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(4).child(0).setText(0, _translate("MainWindow", "Point"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(4).child(1).setText(0, _translate("MainWindow", "Line"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(4).child(2).setText(0, _translate("MainWindow", "Surface"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(4).child(3).setText(0, _translate("MainWindow", "Volume"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(4).child(4).setText(0, _translate("MainWindow", "Duplicate point"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(4).child(5).setText(0, _translate("MainWindow", "Duplicate line"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(4).child(6).setText(0, _translate("MainWindow", "Duplicate surface"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(4).child(7).setText(0, _translate("MainWindow", "Duplicate volume"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(5).setText(0, _translate("MainWindow", "Split"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(5).child(0).setText(0, _translate("MainWindow", "Line"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(6).setText(0, _translate("MainWindow", "Delete"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(6).child(0).setText(0, _translate("MainWindow", "Point"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(6).child(1).setText(0, _translate("MainWindow", "Line"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(6).child(2).setText(0, _translate("MainWindow", "Surface"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(6).child(3).setText(0, _translate("MainWindow", "Volume"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(7).setText(0, _translate("MainWindow", "Coherence"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "Physical groups"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(0).setText(0, _translate("MainWindow", "Add"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(0).child(0).setText(0, _translate("MainWindow", "Point"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(0).child(1).setText(0, _translate("MainWindow", "Line"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(0).child(2).setText(0, _translate("MainWindow", "Surface"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(0).child(3).setText(0, _translate("MainWindow", "Volume"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(1).setText(0, _translate("MainWindow", "Remove"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(1).child(0).setText(0, _translate("MainWindow", "Point"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(1).child(1).setText(0, _translate("MainWindow", "Line"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(1).child(2).setText(0, _translate("MainWindow", "Surface"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(1).child(3).setText(0, _translate("MainWindow", "Volume"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(2).setText(0, _translate("MainWindow", "Reload script"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(3).setText(0, _translate("MainWindow", "Remove last script command"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(4).setText(0, _translate("MainWindow", "Edit script"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Mesh"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "Define"))
        self.treeWidget.topLevelItem(0).child(1).child(0).child(0).setText(0, _translate("MainWindow", "Size fields"))
        self.treeWidget.topLevelItem(0).child(1).child(0).child(1).setText(0, _translate("MainWindow", "Element size at points"))
        self.treeWidget.topLevelItem(0).child(1).child(0).child(2).setText(0, _translate("MainWindow", "Embedded points"))
        self.treeWidget.topLevelItem(0).child(1).child(0).child(3).setText(0, _translate("MainWindow", "Recombine"))
        self.treeWidget.topLevelItem(0).child(1).child(0).child(4).setText(0, _translate("MainWindow", "Transfinite"))
        self.treeWidget.topLevelItem(0).child(1).child(0).child(4).child(0).setText(0, _translate("MainWindow", "Line"))
        self.treeWidget.topLevelItem(0).child(1).child(0).child(4).child(1).setText(0, _translate("MainWindow", "Surface"))
        self.treeWidget.topLevelItem(0).child(1).child(0).child(4).child(2).setText(0, _translate("MainWindow", "Volume"))
        self.treeWidget.topLevelItem(0).child(1).child(0).child(5).setText(0, _translate("MainWindow", "Compound"))
        self.treeWidget.topLevelItem(0).child(1).child(0).child(5).child(0).setText(0, _translate("MainWindow", "Line"))
        self.treeWidget.topLevelItem(0).child(1).child(0).child(5).child(1).setText(0, _translate("MainWindow", "Surface"))
        self.treeWidget.topLevelItem(0).child(1).child(0).child(5).child(2).setText(0, _translate("MainWindow", "Volume"))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "1D"))
        self.treeWidget.topLevelItem(0).child(1).child(2).setText(0, _translate("MainWindow", "2D"))
        self.treeWidget.topLevelItem(0).child(1).child(3).setText(0, _translate("MainWindow", "3D"))
        self.treeWidget.topLevelItem(0).child(1).child(4).setText(0, _translate("MainWindow", "Optimize 3D"))
        self.treeWidget.topLevelItem(0).child(1).child(5).setText(0, _translate("MainWindow", "Optimize 3D (Netgen)"))
        self.treeWidget.topLevelItem(0).child(1).child(6).setText(0, _translate("MainWindow", "Set order 1"))
        self.treeWidget.topLevelItem(0).child(1).child(7).setText(0, _translate("MainWindow", "Set order 2"))
        self.treeWidget.topLevelItem(0).child(1).child(8).setText(0, _translate("MainWindow", "Set order 3"))
        self.treeWidget.topLevelItem(0).child(1).child(9).setText(0, _translate("MainWindow", "High order tools"))
        self.treeWidget.topLevelItem(0).child(1).child(10).setText(0, _translate("MainWindow", "Inspect"))
        self.treeWidget.topLevelItem(0).child(1).child(11).setText(0, _translate("MainWindow", "Refine by splitting"))
        self.treeWidget.topLevelItem(0).child(1).child(12).setText(0, _translate("MainWindow", "Partition"))
        self.treeWidget.topLevelItem(0).child(1).child(13).setText(0, _translate("MainWindow", "Smooth 2D"))
        self.treeWidget.topLevelItem(0).child(1).child(14).setText(0, _translate("MainWindow", "Reclassify 2D"))
        self.treeWidget.topLevelItem(0).child(1).child(15).setText(0, _translate("MainWindow", "Delete"))
        self.treeWidget.topLevelItem(0).child(1).child(15).child(0).setText(0, _translate("MainWindow", "Elements"))
        self.treeWidget.topLevelItem(0).child(1).child(15).child(1).setText(0, _translate("MainWindow", "Lines"))
        self.treeWidget.topLevelItem(0).child(1).child(15).child(2).setText(0, _translate("MainWindow", "Surfaces"))
        self.treeWidget.topLevelItem(0).child(1).child(15).child(3).setText(0, _translate("MainWindow", "Volumes"))
        self.treeWidget.topLevelItem(0).child(1).child(16).setText(0, _translate("MainWindow", "Save"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "GetDP"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Computer command"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "Gmsh"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Mesh Name"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Run"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuRemote.setTitle(_translate("MainWindow", "Remote"))
        self.menuEdit.setTitle(_translate("MainWindow", "Tools"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen_Recent.setText(_translate("MainWindow", "Open Recent"))
        self.actionMerge.setText(_translate("MainWindow", "Merge"))
        self.actionWatch_Pattern.setText(_translate("MainWindow", "Watch Pattern"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionSave_as.setText(_translate("MainWindow", "Rename"))
        self.actionSave_Meth.setText(_translate("MainWindow", "Save As"))
        self.actionSave_Mesh.setText(_translate("MainWindow", "Save Mesh"))
        self.actionSave_Module.setText(_translate("MainWindow", "Save Module Option"))
        self.actionSave_Options_As_Default.setText(_translate("MainWindow", "Save Options As Default"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionOptions.setText(_translate("MainWindow", "Options"))
        self.actionPlugins.setText(_translate("MainWindow", "Plugins"))
        self.actionVisibility.setText(_translate("MainWindow", "Visibility"))
        self.actionClipping.setText(_translate("MainWindow", "Clipping"))
        self.actionManipulator.setText(_translate("MainWindow", "Manipulator"))
        self.actionStatitics.setText(_translate("MainWindow", "Statitics"))
        self.actionMessage_Consol.setText(_translate("MainWindow", "Message Console"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionMerge_2.setText(_translate("MainWindow", "Merge"))
        self.actionClear_2.setText(_translate("MainWindow", "Clear"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionNew_Window.setText(_translate("MainWindow", "New Window"))
        self.actionCopy_To_Clip_Board.setText(_translate("MainWindow", "Copy to Clipboard"))
        self.actionHorizontally.setText(_translate("MainWindow", "Split Horizontally"))
        self.actionSplit_Vertically.setText(_translate("MainWindow", "Split Vertically"))
        self.actionUnsplit.setText(_translate("MainWindow", "Unsplit"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actionZoom.setText(_translate("MainWindow", "Zoom"))
        self.actionEnter_Full_Screen.setText(_translate("MainWindow", "Enter Full Screen"))
        self.actionAttach_Detach_Manu.setText(_translate("MainWindow", "Attach/Detach Manu"))
        self.actionBring_All_To_Front.setText(_translate("MainWindow", "Bring all to Front"))
        self.actionOnline_Document.setText(_translate("MainWindow", "Online Document"))
        self.actionKeyboard_And_Mouse_Usage.setText(_translate("MainWindow", "Keyboard and Mouse Usage"))
        self.actionCurrent_Option_And_Space.setText(_translate("MainWindow", "Current Option and Space"))
        self.actionRestore_all_Options_to_Default_Setting.setText(_translate("MainWindow", "Restore all Options to Default Setting"))
        self.actionAbout_OnelabClient.setText(_translate("MainWindow", "About OnelabClient"))
        self.actionNew.setText(_translate("MainWindow", "New"))

