# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QDialogOptions(object):
    def setupUi(self, QDialogOptions):
        QDialogOptions.setObjectName("QDialogOptions")
        QDialogOptions.resize(561, 420)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QDialogOptions.sizePolicy().hasHeightForWidth())
        QDialogOptions.setSizePolicy(sizePolicy)
        self.listWidget = QtWidgets.QListWidget(QDialogOptions)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 140, 420))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setTabKeyNavigation(False)
        self.listWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.tabWidgetGeneral = QtWidgets.QTabWidget(QDialogOptions)
        self.tabWidgetGeneral.setGeometry(QtCore.QRect(140, -1, 420, 421))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetGeneral.sizePolicy().hasHeightForWidth())
        self.tabWidgetGeneral.setSizePolicy(sizePolicy)
        self.tabWidgetGeneral.setObjectName("tabWidgetGeneral")
        self.General = QtWidgets.QWidget()
        self.General.setAutoFillBackground(True)
        self.General.setObjectName("General")
        self.checkBox = QtWidgets.QCheckBox(self.General)
        self.checkBox.setGeometry(QtCore.QRect(10, 20, 171, 16))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.General)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 50, 131, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.General)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 80, 131, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setAutoRepeat(False)
        self.checkBox_3.setAutoExclusive(False)
        self.checkBox_3.setTristate(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.General)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 110, 141, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.General)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 140, 291, 16))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.General)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 170, 291, 16))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.General)
        self.checkBox_7.setGeometry(QtCore.QRect(10, 200, 161, 16))
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.General)
        self.checkBox_8.setGeometry(QtCore.QRect(10, 230, 151, 16))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.General)
        self.checkBox_9.setGeometry(QtCore.QRect(10, 260, 311, 16))
        self.checkBox_9.setChecked(True)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.General)
        self.checkBox_10.setGeometry(QtCore.QRect(10, 290, 271, 16))
        self.checkBox_10.setChecked(True)
        self.checkBox_10.setObjectName("checkBox_10")
        self.tabWidgetGeneral.addTab(self.General, "")
        self.Advanced = QtWidgets.QWidget()
        self.Advanced.setObjectName("Advanced")
        self.checkBox_11 = QtWidgets.QCheckBox(self.Advanced)
        self.checkBox_11.setGeometry(QtCore.QRect(10, 10, 190, 16))
        self.checkBox_11.setObjectName("checkBox_11")
        self.lineEdit = QtWidgets.QLineEdit(self.Advanced)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.Advanced)
        self.label.setGeometry(QtCore.QRect(130, 40, 111, 16))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Advanced)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 100, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.Advanced)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 70, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(self.Advanced)
        self.label_2.setGeometry(QtCore.QRect(130, 70, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Advanced)
        self.label_3.setGeometry(QtCore.QRect(130, 100, 111, 16))
        self.label_3.setObjectName("label_3")
        self.checkBox_12 = QtWidgets.QCheckBox(self.Advanced)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 130, 271, 16))
        self.checkBox_12.setChecked(True)
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.Advanced)
        self.checkBox_13.setGeometry(QtCore.QRect(10, 160, 271, 16))
        self.checkBox_13.setChecked(True)
        self.checkBox_13.setObjectName("checkBox_13")
        self.pushButton_2 = QtWidgets.QPushButton(self.Advanced)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 155, 100, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox_14 = QtWidgets.QCheckBox(self.Advanced)
        self.checkBox_14.setGeometry(QtCore.QRect(10, 190, 211, 16))
        self.checkBox_14.setObjectName("checkBox_14")
        self.pushButton_3 = QtWidgets.QPushButton(self.Advanced)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 185, 100, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidgetGeneral.addTab(self.Advanced, "")
        self.Axes = QtWidgets.QWidget()
        self.Axes.setObjectName("Axes")
        self.comboBox = QtWidgets.QComboBox(self.Axes)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 121, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.Axes)
        self.label_4.setGeometry(QtCore.QRect(140, 14, 101, 16))
        self.label_4.setObjectName("label_4")
        self.checkBox_15 = QtWidgets.QCheckBox(self.Axes)
        self.checkBox_15.setGeometry(QtCore.QRect(300, 14, 101, 16))
        self.checkBox_15.setObjectName("checkBox_15")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 50, 40, 25))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(50, 50, 40, 25))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(90, 50, 40, 25))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label_5 = QtWidgets.QLabel(self.Axes)
        self.label_5.setGeometry(QtCore.QRect(140, 55, 61, 16))
        self.label_5.setObjectName("label_5")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(10, 80, 40, 25))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(50, 80, 40, 25))
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(90, 80, 40, 25))
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.label_6 = QtWidgets.QLabel(self.Axes)
        self.label_6.setGeometry(QtCore.QRect(140, 85, 71, 16))
        self.label_6.setObjectName("label_6")
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit_7.setGeometry(QtCore.QRect(10, 110, 40, 25))
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.plainTextEdit_8 = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit_8.setGeometry(QtCore.QRect(50, 110, 40, 25))
        self.plainTextEdit_8.setObjectName("plainTextEdit_8")
        self.plainTextEdit_9 = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit_9.setGeometry(QtCore.QRect(90, 110, 40, 25))
        self.plainTextEdit_9.setObjectName("plainTextEdit_9")
        self.label_7 = QtWidgets.QLabel(self.Axes)
        self.label_7.setGeometry(QtCore.QRect(140, 115, 71, 16))
        self.label_7.setObjectName("label_7")
        self.checkBox_16 = QtWidgets.QCheckBox(self.Axes)
        self.checkBox_16.setGeometry(QtCore.QRect(10, 150, 281, 16))
        self.checkBox_16.setChecked(True)
        self.checkBox_16.setObjectName("checkBox_16")
        self.plainTextEdit_10 = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit_10.setGeometry(QtCore.QRect(10, 180, 40, 25))
        self.plainTextEdit_10.setObjectName("plainTextEdit_10")
        self.plainTextEdit_11 = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit_11.setGeometry(QtCore.QRect(50, 180, 40, 25))
        self.plainTextEdit_11.setObjectName("plainTextEdit_11")
        self.plainTextEdit_12 = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit_12.setGeometry(QtCore.QRect(90, 180, 40, 25))
        self.plainTextEdit_12.setObjectName("plainTextEdit_12")
        self.plainTextEdit_13 = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit_13.setGeometry(QtCore.QRect(10, 210, 40, 25))
        self.plainTextEdit_13.setObjectName("plainTextEdit_13")
        self.plainTextEdit_14 = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit_14.setGeometry(QtCore.QRect(50, 210, 40, 25))
        self.plainTextEdit_14.setObjectName("plainTextEdit_14")
        self.plainTextEdit_15 = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit_15.setGeometry(QtCore.QRect(90, 210, 40, 25))
        self.plainTextEdit_15.setObjectName("plainTextEdit_15")
        self.label_8 = QtWidgets.QLabel(self.Axes)
        self.label_8.setGeometry(QtCore.QRect(140, 185, 71, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.Axes)
        self.label_9.setGeometry(QtCore.QRect(140, 210, 71, 16))
        self.label_9.setObjectName("label_9")
        self.checkBox_17 = QtWidgets.QCheckBox(self.Axes)
        self.checkBox_17.setGeometry(QtCore.QRect(10, 250, 111, 16))
        self.checkBox_17.setChecked(True)
        self.checkBox_17.setObjectName("checkBox_17")
        self.plainTextEdit_16 = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit_16.setGeometry(QtCore.QRect(10, 280, 60, 25))
        self.plainTextEdit_16.setObjectName("plainTextEdit_16")
        self.plainTextEdit_17 = QtWidgets.QPlainTextEdit(self.Axes)
        self.plainTextEdit_17.setGeometry(QtCore.QRect(70, 280, 60, 25))
        self.plainTextEdit_17.setObjectName("plainTextEdit_17")
        self.label_10 = QtWidgets.QLabel(self.Axes)
        self.label_10.setGeometry(QtCore.QRect(140, 285, 121, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidgetGeneral.addTab(self.Axes, "")
        self.Aspect = QtWidgets.QWidget()
        self.Aspect.setObjectName("Aspect")
        self.comboBox_2 = QtWidgets.QComboBox(self.Aspect)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 10, 121, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_11 = QtWidgets.QLabel(self.Aspect)
        self.label_11.setGeometry(QtCore.QRect(140, 15, 131, 16))
        self.label_11.setObjectName("label_11")
        self.plainTextEdit_18 = QtWidgets.QPlainTextEdit(self.Aspect)
        self.plainTextEdit_18.setGeometry(QtCore.QRect(10, 40, 121, 25))
        self.plainTextEdit_18.setObjectName("plainTextEdit_18")
        self.label_12 = QtWidgets.QLabel(self.Aspect)
        self.label_12.setGeometry(QtCore.QRect(140, 40, 181, 16))
        self.label_12.setObjectName("label_12")
        self.plainTextEdit_19 = QtWidgets.QPlainTextEdit(self.Aspect)
        self.plainTextEdit_19.setGeometry(QtCore.QRect(10, 70, 60, 25))
        self.plainTextEdit_19.setObjectName("plainTextEdit_19")
        self.plainTextEdit_20 = QtWidgets.QPlainTextEdit(self.Aspect)
        self.plainTextEdit_20.setGeometry(QtCore.QRect(70, 70, 60, 25))
        self.plainTextEdit_20.setObjectName("plainTextEdit_20")
        self.label_13 = QtWidgets.QLabel(self.Aspect)
        self.label_13.setGeometry(QtCore.QRect(140, 70, 161, 16))
        self.label_13.setObjectName("label_13")
        self.checkBox_18 = QtWidgets.QCheckBox(self.Aspect)
        self.checkBox_18.setGeometry(QtCore.QRect(10, 110, 221, 16))
        self.checkBox_18.setObjectName("checkBox_18")
        self.plainTextEdit_21 = QtWidgets.QPlainTextEdit(self.Aspect)
        self.plainTextEdit_21.setGeometry(QtCore.QRect(10, 140, 121, 25))
        self.plainTextEdit_21.setObjectName("plainTextEdit_21")
        self.label_14 = QtWidgets.QLabel(self.Aspect)
        self.label_14.setGeometry(QtCore.QRect(140, 145, 161, 16))
        self.label_14.setObjectName("label_14")
        self.plainTextEdit_22 = QtWidgets.QPlainTextEdit(self.Aspect)
        self.plainTextEdit_22.setGeometry(QtCore.QRect(10, 170, 121, 25))
        self.plainTextEdit_22.setObjectName("plainTextEdit_22")
        self.plainTextEdit_23 = QtWidgets.QPlainTextEdit(self.Aspect)
        self.plainTextEdit_23.setGeometry(QtCore.QRect(10, 200, 121, 25))
        self.plainTextEdit_23.setObjectName("plainTextEdit_23")
        self.comboBox_3 = QtWidgets.QComboBox(self.Aspect)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 230, 121, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.Aspect)
        self.comboBox_4.setGeometry(QtCore.QRect(10, 260, 121, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.plainTextEdit_24 = QtWidgets.QPlainTextEdit(self.Aspect)
        self.plainTextEdit_24.setGeometry(QtCore.QRect(100, 290, 31, 25))
        self.plainTextEdit_24.setObjectName("plainTextEdit_24")
        self.plainTextEdit_25 = QtWidgets.QPlainTextEdit(self.Aspect)
        self.plainTextEdit_25.setGeometry(QtCore.QRect(100, 320, 31, 25))
        self.plainTextEdit_25.setObjectName("plainTextEdit_25")
        self.comboBox_5 = QtWidgets.QComboBox(self.Aspect)
        self.comboBox_5.setGeometry(QtCore.QRect(10, 290, 85, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.Aspect)
        self.comboBox_6.setGeometry(QtCore.QRect(10, 320, 85, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.label_15 = QtWidgets.QLabel(self.Aspect)
        self.label_15.setGeometry(QtCore.QRect(140, 175, 161, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.Aspect)
        self.label_16.setGeometry(QtCore.QRect(140, 205, 161, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.Aspect)
        self.label_17.setGeometry(QtCore.QRect(140, 235, 101, 16))
        self.label_17.setObjectName("label_17")
        self.pushButton = QtWidgets.QPushButton(self.Aspect)
        self.pushButton.setGeometry(QtCore.QRect(250, 230, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_18 = QtWidgets.QLabel(self.Aspect)
        self.label_18.setGeometry(QtCore.QRect(140, 265, 161, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.Aspect)
        self.label_19.setGeometry(QtCore.QRect(140, 295, 101, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.Aspect)
        self.label_20.setGeometry(QtCore.QRect(140, 325, 101, 16))
        self.label_20.setObjectName("label_20")
        self.tabWidgetGeneral.addTab(self.Aspect, "")
        self.Color = QtWidgets.QWidget()
        self.Color.setObjectName("Color")
        self.tabWidgetGeneral.addTab(self.Color, "")
        self.Camera = QtWidgets.QWidget()
        self.Camera.setObjectName("Camera")
        self.tabWidgetGeneral.addTab(self.Camera, "")

        self.retranslateUi(QDialogOptions)
        self.tabWidgetGeneral.setCurrentIndex(2)
        self.checkBox_16.stateChanged['int'].connect(self.plainTextEdit_10.show)
        QtCore.QMetaObject.connectSlotsByName(QDialogOptions)

    def retranslateUi(self, QDialogOptions):
        _translate = QtCore.QCoreApplication.translate
        QDialogOptions.setWindowTitle(_translate("QDialogOptions", "Dialog"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("QDialogOptions", "General"))
        item = self.listWidget.item(1)
        item.setText(_translate("QDialogOptions", "Geometry"))
        item = self.listWidget.item(2)
        item.setText(_translate("QDialogOptions", "Mesh"))
        item = self.listWidget.item(3)
        item.setText(_translate("QDialogOptions", "Solver"))
        item = self.listWidget.item(4)
        item.setText(_translate("QDialogOptions", "Post-Pro"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.checkBox.setText(_translate("QDialogOptions", "Enable export modal"))
        self.checkBox_2.setText(_translate("QDialogOptions", "Use dark interface"))
        self.checkBox_3.setText(_translate("QDialogOptions", "show tooltips"))
        self.checkBox_4.setText(_translate("QDialogOptions", "Show bounding box"))
        self.checkBox_5.setText(_translate("QDialogOptions", "Draw simplified model during user interaction"))
        self.checkBox_6.setText(_translate("QDialogOptions", "Enable mouse hover over meshes"))
        self.checkBox_7.setText(_translate("QDialogOptions", "Enable double buffering"))
        self.checkBox_8.setText(_translate("QDialogOptions", "Enable antialiasing"))
        self.checkBox_9.setText(_translate("QDialogOptions", "Use trackball rotation instead of Euler angles"))
        self.checkBox_10.setText(_translate("QDialogOptions", "Rotate around pseudo  center of mass"))
        self.tabWidgetGeneral.setTabText(self.tabWidgetGeneral.indexOf(self.General), _translate("QDialogOptions", "General"))
        self.checkBox_11.setText(_translate("QDialogOptions", "Print messages on terminal"))
        self.lineEdit.setText(_translate("QDialogOptions", "5"))
        self.label.setText(_translate("QDialogOptions", "Message verbosity"))
        self.lineEdit_2.setText(_translate("QDialogOptions", "5"))
        self.lineEdit_3.setText(_translate("QDialogOptions", "5"))
        self.label_2.setText(_translate("QDialogOptions", "Text editor command"))
        self.label_3.setText(_translate("QDialogOptions", "Default file name"))
        self.checkBox_12.setText(_translate("QDialogOptions", "Ask comfirmation before overwriting files"))
        self.checkBox_13.setText(_translate("QDialogOptions", "Save sesson information on exit"))
        self.pushButton_2.setText(_translate("QDialogOptions", "Show file path"))
        self.checkBox_14.setText(_translate("QDialogOptions", "Save options on exit"))
        self.pushButton_3.setText(_translate("QDialogOptions", "Show file path"))
        self.tabWidgetGeneral.setTabText(self.tabWidgetGeneral.indexOf(self.Advanced), _translate("QDialogOptions", "Advanced"))
        self.comboBox.setItemText(0, _translate("QDialogOptions", "None"))
        self.comboBox.setItemText(1, _translate("QDialogOptions", "Simple axes"))
        self.comboBox.setItemText(2, _translate("QDialogOptions", "Box"))
        self.comboBox.setItemText(3, _translate("QDialogOptions", "Full grid"))
        self.comboBox.setItemText(4, _translate("QDialogOptions", "Open grid"))
        self.comboBox.setItemText(5, _translate("QDialogOptions", "Ruller"))
        self.label_4.setText(_translate("QDialogOptions", "Axes mode"))
        self.checkBox_15.setText(_translate("QDialogOptions", "Mikado style"))
        self.plainTextEdit.setPlainText(_translate("QDialogOptions", "5"))
        self.plainTextEdit_2.setPlainText(_translate("QDialogOptions", "5"))
        self.plainTextEdit_3.setPlainText(_translate("QDialogOptions", "5"))
        self.label_5.setText(_translate("QDialogOptions", "Axes tics"))
        self.plainTextEdit_4.setPlainText(_translate("QDialogOptions", "%.3g"))
        self.plainTextEdit_5.setPlainText(_translate("QDialogOptions", "%.3g"))
        self.plainTextEdit_6.setPlainText(_translate("QDialogOptions", "%.3g"))
        self.label_6.setText(_translate("QDialogOptions", "Axes format"))
        self.label_7.setText(_translate("QDialogOptions", "Axes labels"))
        self.checkBox_16.setText(_translate("QDialogOptions", "Set position and size of axes automatically"))
        self.plainTextEdit_10.setPlainText(_translate("QDialogOptions", "0"))
        self.plainTextEdit_11.setPlainText(_translate("QDialogOptions", "0"))
        self.plainTextEdit_12.setPlainText(_translate("QDialogOptions", "0"))
        self.plainTextEdit_13.setPlainText(_translate("QDialogOptions", "1"))
        self.plainTextEdit_14.setPlainText(_translate("QDialogOptions", "1"))
        self.plainTextEdit_15.setPlainText(_translate("QDialogOptions", "1"))
        self.label_8.setText(_translate("QDialogOptions", "Axes minimum"))
        self.label_9.setText(_translate("QDialogOptions", "Axes maximum"))
        self.checkBox_17.setText(_translate("QDialogOptions", "Show small axes"))
        self.plainTextEdit_16.setPlainText(_translate("QDialogOptions", "-60"))
        self.plainTextEdit_17.setPlainText(_translate("QDialogOptions", "-40"))
        self.label_10.setText(_translate("QDialogOptions", "Small axes position"))
        self.tabWidgetGeneral.setTabText(self.tabWidgetGeneral.indexOf(self.Axes), _translate("QDialogOptions", "Axes"))
        self.comboBox_2.setItemText(0, _translate("QDialogOptions", "Orthographic"))
        self.comboBox_2.setItemText(1, _translate("QDialogOptions", "Perspective"))
        self.label_11.setText(_translate("QDialogOptions", "Projection mode"))
        self.plainTextEdit_18.setPlainText(_translate("QDialogOptions", "5.0"))
        self.label_12.setText(_translate("QDialogOptions", "Z-clipping distance factor"))
        self.plainTextEdit_19.setPlainText(_translate("QDialogOptions", "1.00"))
        self.plainTextEdit_20.setPlainText(_translate("QDialogOptions", "1.00"))
        self.label_13.setText(_translate("QDialogOptions", "Polygon offset factor/unit"))
        self.checkBox_18.setText(_translate("QDialogOptions", "Always apply polygon offset"))
        self.plainTextEdit_21.setPlainText(_translate("QDialogOptions", "6"))
        self.label_14.setText(_translate("QDialogOptions", "Quadric subdivisions"))
        self.plainTextEdit_22.setPlainText(_translate("QDialogOptions", "3.0"))
        self.plainTextEdit_23.setPlainText(_translate("QDialogOptions", "1.0"))
        self.comboBox_3.setItemText(0, _translate("QDialogOptions", "Line"))
        self.comboBox_3.setItemText(1, _translate("QDialogOptions", "Arrow"))
        self.comboBox_3.setItemText(2, _translate("QDialogOptions", "Pyramid"))
        self.comboBox_3.setItemText(3, _translate("QDialogOptions", "3D arrow"))
        self.comboBox_4.setItemText(0, _translate("QDialogOptions", "Native"))
        self.comboBox_4.setItemText(1, _translate("QDialogOptions", "Cairo"))
        self.comboBox_4.setItemText(2, _translate("QDialogOptions", "String Texture"))
        self.plainTextEdit_24.setPlainText(_translate("QDialogOptions", "15"))
        self.plainTextEdit_25.setPlainText(_translate("QDialogOptions", "18"))
        self.comboBox_5.setItemText(0, _translate("QDialogOptions", "Helvetica"))
        self.comboBox_6.setItemText(0, _translate("QDialogOptions", "Helvetica"))
        self.label_15.setText(_translate("QDialogOptions", "Point size"))
        self.label_16.setText(_translate("QDialogOptions", "Line width"))
        self.label_17.setText(_translate("QDialogOptions", "Vector display"))
        self.pushButton.setText(_translate("QDialogOptions", "Edit arrow"))
        self.label_18.setText(_translate("QDialogOptions", "Font rendering engine"))
        self.label_19.setText(_translate("QDialogOptions", "Default font"))
        self.label_20.setText(_translate("QDialogOptions", "Tittle fone"))
        self.tabWidgetGeneral.setTabText(self.tabWidgetGeneral.indexOf(self.Aspect), _translate("QDialogOptions", "Aspect"))
        self.tabWidgetGeneral.setTabText(self.tabWidgetGeneral.indexOf(self.Color), _translate("QDialogOptions", "Color"))
        self.tabWidgetGeneral.setTabText(self.tabWidgetGeneral.indexOf(self.Camera), _translate("QDialogOptions", "Camera"))

